# Generated by Django 2.2.5 on 2022-06-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='livingrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
